import logging
import os

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import FileResponse

from dependencies.auth import require_admin, get_current_user
from schemas.admin_agent_schema import AdminAgentRequest
from agents.admin_agent import AdminAgent
from agents.excel_export import EXPORT_DIR, excel_streaming_response
from agents.image_branding import MEDIA_DIR
from agents.tools.instagram_publish_tool import InstagramPublishTool
from agents.services.approval_service import approval_service
from agents.services.email_service import EmailService

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/admin",
    tags=["Admin AI"],
    dependencies=[Depends(require_admin)],
)

# Separate, unauthenticated router for media Zernio's servers need to
# fetch directly (not through the admin's browser session) when
# publishing to Instagram — require_admin would 401/403 that request
# since Zernio has no admin token to send.
public_media_router = APIRouter(
    prefix="/admin",
    tags=["Admin AI"],
)


agent = AdminAgent()
email_service = EmailService()
instagram_publish_tool = InstagramPublishTool()


@router.post("/ask")
async def ask_admin_agent(
    request: AdminAgentRequest,
    current_user=Depends(get_current_user),
):
    """
    Single entry point for admin requests. Plans which capabilities
    are needed (SQL / Excel / Email / Instagram) and runs them.
    Email and Instagram results come back with status
    "PENDING_APPROVAL" and an approval_id — nothing is actually sent
    or published until /admin/approve/{approval_id} is called.
    """

    user_id = getattr(current_user, "id", None)

    logger.info(
        "POST /admin/ask | user=%s | question=%r",
        user_id, request.question,
    )

    try:
        result = await run_in_threadpool(
            agent.query,
            request.question,
            user_id,
        )
    except Exception:
        logger.exception("POST /admin/ask | user=%s | agent.query failed", user_id)
        raise

    logger.info(
        "POST /admin/ask | user=%s | plan=%s | rows=%d | approvals=%s",
        user_id,
        result.get("plan"),
        len(result.get("rows", [])),
        result.get("approvals"),
    )

    return result


@router.get("/download/{filename}")
async def download_export(filename: str):
    """Serves an Excel report generated by a previous /ask call."""

    # filename is generated server-side (uuid-suffixed) but guard
    # against path traversal from a manipulated filename anyway.
    safe_name = os.path.basename(filename)
    path = os.path.join(EXPORT_DIR, safe_name)

    logger.info("GET /admin/download/%s", safe_name)

    if not os.path.isfile(path):
        logger.warning("GET /admin/download/%s | file not found at %s", safe_name, path)
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(
        path,
        media_type=(
            "application/vnd.openxmlformats-officedocument"
            ".spreadsheetml.sheet"
        ),
        filename=safe_name,
    )


@public_media_router.get("/media/{filename}")
async def get_media(filename: str):
    """
    Serves a branded Instagram post image (logo composited on by
    agents/image_branding.py). This is the URL Zernio's servers fetch
    when publishing, so it must be reachable at PUBLIC_BASE_URL, not
    just from the admin's own browser.
    """

    safe_name = os.path.basename(filename)
    path = os.path.join(MEDIA_DIR, safe_name)

    logger.info("GET /admin/media/%s", safe_name)

    if not os.path.isfile(path):
        logger.warning("GET /admin/media/%s | file not found at %s", safe_name, path)
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(path, media_type="image/png", filename=safe_name)


@router.post("/ask/export")
async def export_admin_agent_result(
    request: AdminAgentRequest,
):
    """
    Runs the full agent flow and, if it produced SQL rows, returns
    them as a downloadable .xlsx instead of JSON. Useful when the
    admin wants to open the result in Excel or share it with someone
    outside the dashboard, regardless of whether they explicitly
    asked for "excel" in the question.
    """

    logger.info("POST /admin/ask/export | question=%r", request.question)

    result = await run_in_threadpool(
        agent.query,
        request.question,
    )

    logger.info(
        "POST /admin/ask/export | rows=%d | building xlsx",
        len(result.get("rows", [])),
    )

    return excel_streaming_response(
        rows=result.get("rows", []),
        question=result.get("question", request.question),
        sql_query=result.get("sql_query", ""),
        answer=result.get("answer", ""),
        filename_prefix="admin_query_result",
    )


@router.get("/approvals/pending")
async def list_pending_approvals():
    pending = approval_service.list_pending()
    logger.info("GET /admin/approvals/pending | count=%d", len(pending))
    return pending


@router.get("/approvals/{approval_id}")
async def get_approval(approval_id: str):
    approval = approval_service.get(approval_id)

    if not approval:
        logger.warning("GET /admin/approvals/%s | not found", approval_id)
        raise HTTPException(status_code=404, detail="Approval not found")

    return approval


@router.post("/approve/{approval_id}")
async def approve_action(
    approval_id: str,
    image_url: str | None = Query(
        default=None,
        description=(
            "Optional. For instagram approvals only — attach or "
            "override the image to publish, in case automatic image "
            "generation failed or the admin wants a different image."
        ),
    ),
):
    """
    Approves a pending email or Instagram action and immediately
    executes it (sends the email / publishes the post). This is the
    "Human approves" -> "Send / Publish" step in the agent flow.
    """

    logger.info("POST /admin/approve/%s | image_url_override=%s", approval_id, bool(image_url))

    try:
        approval = approval_service.mark_approved(approval_id)
    except KeyError:
        logger.warning("POST /admin/approve/%s | not found", approval_id)
        raise HTTPException(status_code=404, detail="Approval not found")
    except ValueError as e:
        logger.warning("POST /admin/approve/%s | %s", approval_id, e)
        raise HTTPException(status_code=409, detail=str(e))

    logger.info(
        "POST /admin/approve/%s | action_type=%s | marked APPROVED, executing",
        approval_id, approval["action_type"],
    )

    if approval["action_type"] == "instagram" and image_url:
        approval = approval_service.update_payload(
            approval_id,
            image_url=image_url,
        )

    try:
        if approval["action_type"] == "email":
            payload = approval["payload"]

            logger.info(
                "POST /admin/approve/%s | sending email | recipients=%d | subject=%r",
                approval_id, len(payload["recipients"]), payload["subject"],
            )

            send_result = await run_in_threadpool(
                email_service.send_email,
                payload["recipients"],
                payload["subject"],
                payload["body"],
            )

            # send_email() returns {"status": "skipped", ...} instead
            # of raising when there are no recipients — don't let
            # that silently look like a successful send.
            if send_result.get("status") == "skipped":
                logger.warning(
                    "POST /admin/approve/%s | email skipped: no recipients",
                    approval_id,
                )
                raise RuntimeError(
                    "No recipients were found for this email, so "
                    "nothing was sent. This usually means the SQL "
                    "query behind this request didn't match any "
                    "customers, or didn't return an email column."
                )

            logger.info(
                "POST /admin/approve/%s | email sent | result=%s",
                approval_id, send_result,
            )

            approval_service.mark_executed(approval_id, send_result)

        elif approval["action_type"] == "instagram":
            payload = approval["payload"]

            if not payload.get("image_url"):
                logger.warning(
                    "POST /admin/approve/%s | no image_url set, aborting publish",
                    approval_id,
                )
                raise RuntimeError(
                    "No image_url is set for this Instagram post. "
                    "Retry with ?image_url=... to attach one before "
                    "publishing."
                )

            logger.info(
                "POST /admin/approve/%s | publishing to instagram | image_url=%s",
                approval_id, payload["image_url"],
            )

            publish_result = await instagram_publish_tool.publish(
                image_url=payload["image_url"],
                caption=payload["caption"],
                approved=True,
            )

            logger.info(
                "POST /admin/approve/%s | published | result=%s",
                approval_id, publish_result,
            )

            approval_service.mark_executed(approval_id, publish_result)

        else:
            raise RuntimeError(
                f"Unknown action_type: {approval['action_type']}"
            )

    except Exception as e:
        logger.exception("POST /admin/approve/%s | execution failed", approval_id)
        approval_service.mark_failed(approval_id, str(e))
        raise HTTPException(status_code=500, detail=str(e))

    return approval_service.get(approval_id)


@router.post("/reject/{approval_id}")
async def reject_action(approval_id: str):
    logger.info("POST /admin/reject/%s", approval_id)

    try:
        return approval_service.reject(approval_id)
    except KeyError:
        logger.warning("POST /admin/reject/%s | not found", approval_id)
        raise HTTPException(status_code=404, detail="Approval not found")
    except ValueError as e:
        logger.warning("POST /admin/reject/%s | %s", approval_id, e)
        raise HTTPException(status_code=409, detail=str(e))