import os

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import FileResponse

from dependencies.auth import require_admin, get_current_user
from schemas.admin_agent_schema import AdminAgentRequest
from agents.admin_agent import AdminAgent
from agents.excel_export import EXPORT_DIR, excel_streaming_response
from agents.tools.instagram_publish_tool import InstagramPublishTool
from agents.services.approval_service import approval_service
from agents.services.email_service import EmailService

router = APIRouter(
    prefix="/admin",
    tags=["Admin AI"],
    dependencies=[Depends(require_admin)],
)


agent = AdminAgent()
email_service = EmailService()
instagram_publish_tool = InstagramPublishTool()


@router.post("/ask")
async def ask_admin_agent(
    request: AdminAgentRequest,
    current_user=Depends(get_current_user),
):
    """
    Single entry point for admin requests. Plans which capabilities
    are needed (SQL / Excel / Email / Instagram) and runs them.
    Email and Instagram results come back with status
    "PENDING_APPROVAL" and an approval_id — nothing is actually sent
    or published until /admin/approve/{approval_id} is called.
    """

    result = await run_in_threadpool(
        agent.query,
        request.question,
        getattr(current_user, "id", None),
    )

    return result


@router.get("/download/{filename}")
async def download_export(filename: str):
    """Serves an Excel report generated by a previous /ask call."""

    # filename is generated server-side (uuid-suffixed) but guard
    # against path traversal from a manipulated filename anyway.
    safe_name = os.path.basename(filename)
    path = os.path.join(EXPORT_DIR, safe_name)

    if not os.path.isfile(path):
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(
        path,
        media_type=(
            "application/vnd.openxmlformats-officedocument"
            ".spreadsheetml.sheet"
        ),
        filename=safe_name,
    )


@router.post("/ask/export")
async def export_admin_agent_result(
    request: AdminAgentRequest,
):
    """
    Runs the full agent flow and, if it produced SQL rows, returns
    them as a downloadable .xlsx instead of JSON. Useful when the
    admin wants to open the result in Excel or share it with someone
    outside the dashboard, regardless of whether they explicitly
    asked for "excel" in the question.
    """

    result = await run_in_threadpool(
        agent.query,
        request.question,
    )

    return excel_streaming_response(
        rows=result.get("rows", []),
        question=result.get("question", request.question),
        sql_query=result.get("sql_query", ""),
        answer=result.get("answer", ""),
        filename_prefix="admin_query_result",
    )


@router.get("/approvals/pending")
async def list_pending_approvals():
    return approval_service.list_pending()


@router.get("/approvals/{approval_id}")
async def get_approval(approval_id: str):
    approval = approval_service.get(approval_id)

    if not approval:
        raise HTTPException(status_code=404, detail="Approval not found")

    return approval


@router.post("/approve/{approval_id}")
async def approve_action(
    approval_id: str,
    image_url: str | None = Query(
        default=None,
        description=(
            "Optional. For instagram approvals only — attach or "
            "override the image to publish, in case automatic image "
            "generation failed or the admin wants a different image."
        ),
    ),
):
    """
    Approves a pending email or Instagram action and immediately
    executes it (sends the email / publishes the post). This is the
    "Human approves" -> "Send / Publish" step in the agent flow.
    """

    try:
        approval = approval_service.mark_approved(approval_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Approval not found")
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))

    if approval["action_type"] == "instagram" and image_url:
        approval = approval_service.update_payload(
            approval_id,
            image_url=image_url,
        )

    try:
        if approval["action_type"] == "email":
            payload = approval["payload"]

            send_result = await run_in_threadpool(
                email_service.send_email,
                payload["recipients"],
                payload["subject"],
                payload["body"],
            )

            approval_service.mark_executed(approval_id, send_result)

        elif approval["action_type"] == "instagram":
            payload = approval["payload"]

            if not payload.get("image_url"):
                raise RuntimeError(
                    "No image_url is set for this Instagram post. "
                    "Retry with ?image_url=... to attach one before "
                    "publishing."
                )

            publish_result = await instagram_publish_tool.publish(
                image_url=payload["image_url"],
                caption=payload["caption"],
                approved=True,
            )

            approval_service.mark_executed(approval_id, publish_result)

        else:
            raise RuntimeError(
                f"Unknown action_type: {approval['action_type']}"
            )

    except Exception as e:
        approval_service.mark_failed(approval_id, str(e))
        raise HTTPException(status_code=500, detail=str(e))

    return approval_service.get(approval_id)


@router.post("/reject/{approval_id}")
async def reject_action(approval_id: str):
    try:
        return approval_service.reject(approval_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Approval not found")
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
