"""add card type

Revision ID: 061e126fc99c
Revises: c3f6a91d2e47
Create Date: 2026-08-14 16:04:29.949080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061e126fc99c'
down_revision: Union[str, Sequence[str], None] = 'c3f6a91d2e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('type', sa.String(length=6), nullable=False, server_default="DEBIT"))
    op.alter_column(
        "cards",
        "type",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'type')
    # ### end Alembic commands ###
