"""update user and account schema

Revision ID: 100
Revises: b91e83c70a42
Create Date: 2026-08-13 21:10:32.207802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '100'
down_revision: Union[str, Sequence[str], None] = 'b91e83c70a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.String(length=20), server_default='SAVINGS', nullable=False))
    op.add_column('accounts', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('accounts', sa.Column('close_reason', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('accounts', 'account_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('accounts', 'opened_at')
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('address_line', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('county', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('postcode', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'postcode')
    op.drop_column('users', 'county')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address_line')
    op.drop_column('users', 'dob')
    op.add_column('accounts', sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('accounts', 'account_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'close_reason')
    op.drop_column('accounts', 'is_deleted')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'branch')
    # ### end Alembic commands ###
