"""altered user and account table

Revision ID: 100
Revises: b91e83c70a42
Create Date: 2026-08-13 17:38:37.893842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100'
down_revision: Union[str, Sequence[str], None] = 'b91e83c70a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.String(length=20), server_default='savings', nullable=False))
    op.add_column('accounts', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('accounts', sa.Column('close_reason', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('accounts', 'account_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo_document_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_users_google_subject'), table_name='users')
    op.create_foreign_key(None, 'users', 'documents', ['photo_document_id'], ['id'])
    op.drop_column('users', 'google_subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_google_subject'), 'users', ['google_subject'], unique=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'status')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'country')
    op.drop_column('users', 'photo_document_id')
    op.drop_column('users', 'address')
    op.drop_column('users', 'dob')
    op.alter_column('accounts', 'account_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'close_reason')
    op.drop_column('accounts', 'is_deleted')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'branch')
    # ### end Alembic commands ###
