"""add created_at to consultants

Revision ID: 3b94686cb95e
Revises: 962fbd89c297
Create Date: 2026-08-03 11:36:01.773215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b94686cb95e'
down_revision: Union[str, Sequence[str], None] = '962fbd89c297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('consultants', 'batch',
               existing_type=postgresql.ENUM('PYTHON', 'JAVA', 'DATA', 'ANDROID', name='batch'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultants', 'batch',
               existing_type=postgresql.ENUM('PYTHON', 'JAVA', 'DATA', 'ANDROID', name='batch'),
               nullable=False)
    op.drop_column('consultants', 'created_at')
    # ### end Alembic commands ###
