"""add campaigns table

Revision ID: 45fbdc3c2506
Revises: 0eade7147e1b
Create Date: 2026-08-28 12:20:46.963069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45fbdc3c2506'
down_revision: Union[str, Sequence[str], None] = '0eade7147e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('campaign_type', sa.Enum('EMAIL', 'INSTAGRAM', 'EMAIL_AND_INSTAGRAM', name='campaigntype'), nullable=False),
    sa.Column('audience_description', sa.Text(), nullable=True),
    sa.Column('audience_query', sa.Text(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('instagram_caption', sa.Text(), nullable=True),
    sa.Column('instagram_image_prompt', sa.Text(), nullable=True),
    sa.Column('instagram_image_url', sa.Text(), nullable=True),
    sa.Column('instagram_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.drop_column('loans', 'accrued_interest')
    op.drop_column('loans', 'last_interest_calculated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('last_interest_calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('loans', sa.Column('accrued_interest', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
