"""add user role

Revision ID: 5fe56d3f793d
Revises: 123f96953cb6
Create Date: 2026-07-25 13:44:01.337983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe56d3f793d'
down_revision: Union[str, Sequence[str], None] = '123f96953cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum(
        "USER",
        "ADMIN",
        name="role",
    )
    role_enum.create(
        op.get_bind(),
        checkfirst=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            role_enum,
            nullable=False,
            server_default="USER",
        ),
    )
    op.execute(
        """
        UPDATE users
        SET role = 'ADMIN'
        WHERE email = 'admin@informationtechconsultants.co.uk'
        """
    )
    op.alter_column(
        "users",
        "role",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
