"""drop consultants table

Revision ID: 7dae6266af8f
Revises: 3b94686cb95e
Create Date: 2026-08-06 19:48:08.235092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dae6266af8f'
down_revision: Union[str, Sequence[str], None] = '3b94686cb95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultants_id'), table_name='consultants')
    op.drop_table('consultants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch', postgresql.ENUM('PYTHON', 'JAVA', 'DATA', 'ANDROID', name='batch'), autoincrement=False, nullable=True),
    sa.Column('placement_status', postgresql.ENUM('ONBOARDING', 'TRAINING', 'AVAILABLE', 'PLACED', 'ENDING_SOON', name='placement_status'), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('consultants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consultants_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('consultants_user_id_key'))
    )
    op.create_index(op.f('ix_consultants_id'), 'consultants', ['id'], unique=False)
    # ### end Alembic commands ###
