"""removed_document_id_and_added_status_in_user

Revision ID: e142528b46cd
Revises: 100
Create Date: 2026-08-14 11:48:30.369903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e142528b46cd'
down_revision: Union[str, Sequence[str], None] = '100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_document_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'document_id')
    op.add_column('users', sa.Column('user_status', sa.String(length=20), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_status')
    op.add_column('accounts', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('accounts_document_id_fkey'), 'accounts', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
