"""add accrued interest column to loans

Revision ID: e70dc07cc508
Revises: e2e2b61f4210
Create Date: 2026-08-24 13:55:09.464628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70dc07cc508'
down_revision: Union[str, Sequence[str], None] = 'e2e2b61f4210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('accrued_interest', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'accrued_interest')
    # ### end Alembic commands ###
