"""add consultant profiles and user names

Revision ID: f697789de33d
Revises: 5fe56d3f793d
Create Date: 2026-08-02 11:33:12.932497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f697789de33d'
down_revision: Union[str, Sequence[str], None] = '5fe56d3f793d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=100), nullable=False),
    sa.Column('placement_status', sa.Enum('ONBOARDING', 'TRAINING', 'AVAILABLE', 'PLACED', name='placement_status'), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_consultants_id'), 'consultants', ['id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_consultants_id'), table_name='consultants')
    op.drop_table('consultants')
    # ### end Alembic commands ###
